#!/usr/bin/env bash
cd /workspace/rpg_svo/svo
mkdir -p build_valgrind && cd build_valgrind
cmake -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_CXX_FLAGS="-g -O0 -fno-omit-frame-pointer" \
  -DSophus_DIR=/workspace/Sophus/build \
  -Dfast_DIR=/workspace/fast/build \
  -Dvikit_common_DIR=/workspace/rpg_vikit/vikit_common/build ..
make -j$(nproc)
